import CryptoKit
import Foundation

enum ClipboardContentRules {
  enum ContentDomain: String {
    case text
    case url
    case image
    case file
  }

  private static let sensitiveTypeIdentifiers: Set<String> = [
    "org.nspasteboard.concealedtype",
    "org.nspasteboard.transienttype",
    "org.nspasteboard.autogeneratedtype",
    "com.apple.pasteboard.concealed",
    "com.agilebits.onepassword",
    "com.agilebits.onepassword.find-pasteboard",
  ]

  static func sha256(_ data: Data) -> String {
    hexDigest(SHA256.hash(data: data))
  }

  static func contentHash(domain: ContentDomain, data: Data) -> String {
    var hasher = SHA256()
    hasher.update(data: Data(domain.rawValue.utf8))
    hasher.update(data: Data([0]))
    hasher.update(data: data)
    return hexDigest(hasher.finalize())
  }

  static func isDuplicateOfMostRecent(
    capturedHash: String,
    mostRecentHash: String?
  ) -> Bool {
    mostRecentHash == capturedHash
  }

  static func wholeURL(in text: String) -> String? {
    let candidate = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !candidate.isEmpty else { return nil }

    guard
      let detector = try? NSDataDetector(
        types: NSTextCheckingResult.CheckingType.link.rawValue
      )
    else {
      return nil
    }

    let range = NSRange(candidate.startIndex..<candidate.endIndex, in: candidate)
    guard
      let match = detector.firstMatch(in: candidate, options: [], range: range),
      match.resultType == .link,
      match.range == range,
      let url = match.url
    else {
      return nil
    }

    return url.absoluteString
  }

  static func containsSensitivePasteboardType(_ identifiers: [String]) -> Bool {
    identifiers.contains { identifier in
      let normalized = identifier.lowercased()
      return sensitiveTypeIdentifiers.contains(normalized)
        || normalized.contains("pasteboard.concealed")
        || normalized.contains("pasteboard.password")
    }
  }

  static func isIgnoredBundleID(
    _ bundleID: String,
    ignoredBundleIDs: [String]
  ) -> Bool {
    ignoredBundleIDs.contains {
      $0.compare(bundleID, options: .caseInsensitive) == .orderedSame
    }
  }

  static func fileContentHash(
    bookmarkData: Data,
    fallbackIdentity: String
  ) -> String {
    do {
      let resolved = try SecurityScopedBookmark.resolve(bookmarkData)
      let didStartAccessing = resolved.url.startAccessingSecurityScopedResource()
      defer {
        if didStartAccessing {
          resolved.url.stopAccessingSecurityScopedResource()
        }
      }

      let values = try resolved.url.resourceValues(
        forKeys: [.isRegularFileKey]
      )
      guard values.isRegularFile == true else {
        return contentHash(
          domain: .file,
          data: Data(fallbackIdentity.utf8)
        )
      }

      return try sha256File(at: resolved.url, domain: .file)
    } catch {
      return contentHash(
        domain: .file,
        data: Data(fallbackIdentity.utf8)
      )
    }
  }

  static func sha256File(
    at url: URL,
    domain: ContentDomain? = nil
  ) throws -> String {
    let handle = try FileHandle(forReadingFrom: url)
    defer {
      try? handle.close()
    }

    var hasher = SHA256()
    if let domain {
      hasher.update(data: Data(domain.rawValue.utf8))
      hasher.update(data: Data([0]))
    }

    while let chunk = try handle.read(upToCount: 1_048_576), !chunk.isEmpty {
      hasher.update(data: chunk)
    }

    return hexDigest(hasher.finalize())
  }

  private static func hexDigest<Digest: Sequence>(_ digest: Digest) -> String
  where Digest.Element == UInt8 {
    digest
      .map { String(format: "%02x", $0) }
      .joined()
  }
}
